In [1]:
import random, shutil, os
import numpy as np
import pandas as pd

from mido import Message, MidiFile, MidiTrack
from glob import glob

In [ ]:
def create_only_folders(dir, files):
    return [f for f in files if os.path.isfile(os.path.join(dir,f))]


shutil.copytree(r"C:\Users\KIST\Desktop\MIDI", './bar_dataset_0119', ignore=create_only_folders)

In [2]:
len(glob(r"C:\Users\KIST\Desktop\MIDI\gmd\**\**\*.mid"))

1150

In [14]:
midi_list = glob(r"C:\Users\KIST\Desktop\MIDI\**\**\**\*.mid")

# midi_list = glob(r"C:\Users\KIST\Desktop\asdf\*.mid")

In [2]:
def classify(note, midi):
    
    cat = ''

    if 'gmd' in midi.lower():

        if note in [36]: # kick
            cat = 0
        elif note in [38, 40, 37]: # snare 
            cat = 1
        elif note in [48, 50]: # High Tom
            cat = 2
            # cat = 2 # Replace HT -> MT
        elif note in [45, 47]: # Mid Tom
            cat = 3
            # cat = 2
        elif note in [43, 58]: # Low Tom
            cat = 4
            # cat = 3
        elif note in [46, 26]: # Open Hat
            cat = 5
            # cat = 4
        elif note in [42, 22, 44]: # Closed Hat
            cat = 6
            # cat = 5
        elif note in [49, 55, 57, 52]: # Crash
            cat = 7 
            # cat = 6 # Replace Cr -> Ri
        elif note in [51, 59, 53]: # Ride
            # cat = 6
            cat = 8
        else:
            cat = 9
    
    else:
        if note in [35, 36]: # kick
            cat = 0
        elif note in [37, 38, 39, 40]: # snare 
            cat = 1
        elif note in [48, 50]: # High Tom
            # cat = 2
            cat = 2 # Replace HT -> MT
        elif note in [45, 47]: # Mid Tom
            cat = 3
            # cat = 2
        elif note in [41, 43]: # Low Tom
            cat = 4
            # cat = 3
        elif note in [46]: # Open Hat
            cat = 5
            # cat = 4
        elif note in [42, 44]: # Closed Hat
            cat = 6
            # cat = 5
        elif note in [49, 55, 57, 52]: # Crash
            cat = 7 
            # cat = 6 # Replace Cr -> Ri
        elif note in [51, 59, 53]: # Ride
            # cat = 6
            cat = 8
        else:
            cat = 9

    return cat

def gm_kit_classify(note):
    cat = ''
    if note in [35, 36]: # kick
        cat = 0
    elif note in [37, 38, 39, 40]: # snare 
        cat = 1
    elif note in [48, 50]: # High Tom
        cat = 2
        # cat = 2 # Replace HT -> MT
    elif note in [45, 47]: # Mid Tom
        cat = 3
        # cat = 2
    elif note in [41, 43]: # Low Tom
        cat = 4
        # cat = 3
    elif note in [46]: # Open Hat
        cat = 5
        # cat = 4
    elif note in [42, 44]: # Closed Hat
        cat = 6
        # cat = 5
    elif note in [49, 55, 57, 52]: # Crash
        cat = 7 
        # cat = 6 # Replace Cr -> Ri
    elif note in [51, 59, 53]: # Ride
        # cat = 6
        cat = 8
    else:
        cat = 9

    return cat

def in_gmd(note):
    if note in [36, 38, 40, 37, 48, 50, 45, 47, 43, 58, 46, 26, 42, 22, 44, 49, 55, 57, 52, 51, 59, 53]:
        return True
    else:
        return False

def in_gm(note):
    if note in [35, 36, 37, 38, 39, 40, 48, 50, 45, 47, 41, 43, 46, 42, 44, 49, 55, 57, 52, 51, 59, 53]:
        return True
    else:
        return False
        

In [5]:
mid = MidiFile(midi_list[1], clip=True)

In [6]:
midi_list[1]

'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\eval_session\\1_funk-groove1_138_beat_4-4.mid'

In [31]:
for msg in mid.tracks[0]:
    print(msg)

MetaMessage('track_name', name='SI-Drum Kit 1', time=0)
note_on channel=0 note=35 velocity=102 time=0
note_on channel=0 note=36 velocity=114 time=0
note_off channel=0 note=35 velocity=102 time=98
note_off channel=0 note=36 velocity=114 time=45
note_on channel=0 note=35 velocity=110 time=97
note_on channel=0 note=36 velocity=115 time=0
note_on channel=0 note=38 velocity=115 time=240
note_on channel=0 note=43 velocity=111 time=0
note_off channel=0 note=35 velocity=110 time=49
note_off channel=0 note=36 velocity=115 time=26
note_off channel=0 note=38 velocity=115 time=120
note_on channel=0 note=35 velocity=102 time=45
note_on channel=0 note=36 velocity=118 time=0
note_off channel=0 note=43 velocity=111 time=19
note_off channel=0 note=35 velocity=102 time=90
note_off channel=0 note=36 velocity=118 time=71
note_on channel=0 note=35 velocity=113 time=60
note_on channel=0 note=36 velocity=119 time=0
note_off channel=0 note=36 velocity=119 time=259
note_on channel=0 note=38 velocity=115 time=1

In [17]:
len(midi_list)

2074

In [7]:
import random

In [9]:
# mid2 = MidiFile('/Users/cooky/Desktop/groove/drummer7/session1/3_rock_86_fill_4-4.mid', clip=True)
cnt = 0
imsi = {}

for midi in files:
# for midi in midi_list:

    lst = []
    
    mid = MidiFile(midi, clip=True)
    on_sec = 0
    event = []
    quantize = 120
    if 'monkee' in midi.lower():
        quantize = 60
    elif 'longloops2' in midi.lower():
        quantize = 24

    # if 'fill' not in midi.lower():
        # print(midi)
    # print(len(mid.tracks))
    
    for msg in mid.tracks[mid.tracks.__len__() - 1]:
        # print(msg)
        note = str(msg).split()

        if len(note) == 5:
            on_sec += msg.dict()['time']

            if note[0] == 'note_on' and note[3] != 'velocity=0':
                # print(note)
                if [round(on_sec/quantize), msg.dict()['note']] not in event:
                    event.append([round(on_sec/quantize), msg.dict()['note']])
    # print(midi)
    # print(event)
    beat = pd.DataFrame(0, columns = np.arange(10), index = np.arange(event[-1][0] + 1))

    
    for e in event:
        beat.loc[e[0], classify(e[1], midi=midi)] = 1
        # print(e)
        # print(beat)
        
    # print(beat)
    beat = beat.drop(9, axis=1)
    
    beat.to_csv('./0217/' + str(cnt) + '.csv', index=False, header=False)
    # beat.to_csv(str(cnt) + '.csv.gzip', index=False, compression='gzip')
    cnt += 1

    


In [20]:
files

['C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session1\\40_hiphop_100_beat_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\240_funk-purdieshuffle_130_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\50_punk_128_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\119_afrocuban-bembe_122_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\111 BPM TOP FUNK\\Verse 003 (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\195_reggae_78_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Pop\\075 6-8 Pop Stick Fill 5.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\R&B\\113 Boogaloo Fill 1.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\115 BPM POPCORN FUNK\\Hihat 001 (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variet

In [6]:
pd.read_csv('./0130/0.csv.gzip',compression='gzip')


0  1  2  3  4  5  6  7  8
0    0  1  0  0  0  0  0  0  0
1    0  1  0  0  0  0  0  0  0
2    1  0  0  0  0  0  0  0  0
3    0  1  0  0  0  0  0  0  0
4    0  0  0  0  0  0  1  0  0
..  .. .. .. .. .. .. .. .. ..
106  0  0  0  0  0  0  1  0  0
107  0  0  0  0  0  0  1  0  0
108  0  0  0  0  0  0  1  0  0
109  0  0  0  0  0  0  1  0  0
110  0  0  0  0  0  0  1  0  0

[111 rows x 9 columns]

In [7]:
# mid2 = MidiFile('/Users/cooky/Desktop/groove/drummer7/session1/3_rock_86_fill_4-4.mid', clip=True)
cnt = 0
imsi = {}

for midi in midi_list:

    lst = []
    
    mid = MidiFile(midi, clip=True)
    on_sec = 0
    event = []
    quantize = 120
    if 'monkee' in midi.lower():
        quantize = 60
    elif 'longloops2' in midi.lower():
        quantize = 24

    # if 'fill' not in midi.lower():
        # print(midi)
    
    for msg in mid.tracks[mid.tracks.__len__() - 1]:

        note = str(msg).split()

        if len(note) == 5:
            on_sec += msg.dict()['time']

            if note[0] == 'note_on':
                if [round(on_sec/120), msg.dict()['note']] not in event:
                    event.append([round(on_sec/120), msg.dict()['note']])
    # print(midi)
    # print(event)
    beat = pd.DataFrame(0, columns = np.arange(10), index = np.arange(event[-1][0] + 1))
    
    
    for e in event:
        beat.loc[e[0], classify(e[1], midi=midi)] = 1
            
        # print(beat)
        
        # beat.to_csv('./midi2df_0109/beat/' + str(cnt) + '.csv.gzip', index=False, compression='gzip')
        # beat.to_csv(str(cnt) + '.csv.gzip', index=False, compression='gzip')
    cnt += 1
        

    asd = beat.drop(9, axis=1)
    
    for ii in np.array(asd):
        if list(ii) in checking_arr:
            lst.append(checking_arr.index(list(ii)))
        else:
            lst.append('err')
    if 'err' not in list(set(lst)):
        # print(midi)
        # print(set(lst))
        # print('---')
        imsi[midi] = list(set(lst))

while True:
    files = []
    l_29 = []
    for i in range(150):
        k = random.choice(list(imsi.keys()))
        files.append(k)
        for j in imsi[k]:
            l_29.append(j)
    l_29 = list(set(l_29))
    if len(l_29) == 30:
        break
    

    


NameError: name 'midi_list' is not defined

In [37]:
pd.read_csv('./0130/0.csv.gzip',compression='gzip')

0  1  2  3  4  5  6  7  8
0    0  1  0  0  0  0  0  0  0
1    0  1  0  0  0  0  0  0  0
2    1  0  0  0  0  0  0  0  0
3    0  1  0  0  0  0  0  0  0
4    0  0  0  0  0  0  1  0  0
..  .. .. .. .. .. .. .. .. ..
106  0  0  0  0  0  0  1  0  0
107  0  0  0  0  0  0  1  0  0
108  0  0  0  0  0  0  1  0  0
109  0  0  0  0  0  0  1  0  0
110  0  0  0  0  0  0  1  0  0

[111 rows x 9 columns]

In [3]:
files = ['C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session1\\40_hiphop_100_beat_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\240_funk-purdieshuffle_130_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\50_punk_128_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\119_afrocuban-bembe_122_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\111 BPM TOP FUNK\\Verse 003 (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\195_reggae_78_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Pop\\075 6-8 Pop Stick Fill 5.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\R&B\\113 Boogaloo Fill 1.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\115 BPM POPCORN FUNK\\Hihat 001 (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Pop\\120 4-To-The-Floor Fill 1.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\15_country_114_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\173_afrocuban-rhumba_110_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer3\\session1\\49_rock_120_beat_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\136_afrocuban-bembe_122_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session1\\7_rock_93_beat_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\110 BPM TOP FUNK\\Hihat 007 (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Blues\\128 Blues Rumba.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\79_punk_144_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\LongLoops2_MIDILoops\\MIDI Loops\\Songwriter - 4 Bars\\Songwriter_4Bar_01.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\LongLoops2_MIDILoops\\MIDI Loops\\Songwriter - 8 Bars\\Songwriter_8Bar_14.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\18_country_114_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\130_funk-fast_125_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\R&B\\135 Half-Time Shuffle Fill 3.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\LongLoops2_MIDILoops\\MIDI Loops\\Songwriter - 4 Bars\\Songwriter_4Bar_01.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Electronic\\140 Trance Beat Fill 4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Pop\\075 6-8 Pop Stick Fill 2.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\080 BPM WESTCOAST FUNK\\Hihat 004 (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\eval_session\\7_pop-groove7_138_beat_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\R&B\\150 Motown Beat Fill 3.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session2\\16_rock_118_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Electronic\\140 Trance Beat Fill 1.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\48_punk_128_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Rock\\120 Floor Tom Rock Crash.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\World\\190 Cumbia Fill 3.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer3\\session2\\14_rock_100_beat_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Funk\\110 Get Up Fill 2.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Electronic\\160 DnB Beat 2.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Country\\120 Heatbeat Fill 1.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Hip Hop\\088 Hip Hop 7 Fill 3.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\110 BPM TOP FUNK\\Hihat 001 (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\110 BPM TOP FUNK\\Hihat 006 (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\095 BPM FUNK ROCK\\Theme 001 Hihat (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer3\\session2\\25_hiphop_92_beat_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\59_punk_128_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Pop\\120 4-To-The-Floor Fill 4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\36_punk_128_beat_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\LongLoops2_MIDILoops\\MIDI Loops\\Songwriter - 4 Bars\\Songwriter_4Bar_01.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Pop\\075 6-8 Pop Stick Fill 5.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\111_funk_95_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\8_jazz-funk_116_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Metal\\174 2-Feel Fill 6.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Rock\\140 Driving Rock 1 Fill 3.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\38_punk_128_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\184_rock_115_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session2\\61_soul-motown_148_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Hip Hop\\088 Hip Hop 4 Fill 2.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\115 BPM POPCORN FUNK\\Ride 009 (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\151_gospel_120_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Hip Hop\\092 Hip Hop 3 Fill 2.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Pop\\100 Pop 8th Feel Crash.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Blues\\078 Slow Blues Fill 1.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session2\\31_rock_75_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Funk\\088 16th Funk.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Hip Hop\\090 Hip Hop 2 Fill 2.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\20_jazz-funk_116_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\162_afrocuban-rhumba_110_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\186_rock_115_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Metal\\150 DBeat Ride.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\World\\100 Bembe Fill 4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Electronic\\150 Jungle Displaced Fill 3.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\138 BPM FUSION FUNK\\Hihat 006 (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\100_funk-rock_92_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\World\\190 Cumbia Fill 2.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\188_reggae_78_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Pop\\100 Pop 16th Feel Fill 3.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Rock\\140 Driving Rock 1 Crash.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer3\\session2\\25_hiphop_92_beat_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\R&B\\135 Half-Time Shuffle Fill 2.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session3\\40_rock-indie_63_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\250_funk-purdieshuffle_130_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Rock\\120 Rock Basic 2 Fill 1.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session1\\6_rock_86_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\145_gospel_120_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Metal\\150 DBeat OH.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Hip Hop\\090 Busy Beat Fill 1.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Funk\\129 Jab-OH.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Country\\120 Heatbeat Fill 4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\53_punk_128_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Hip Hop\\088 Hip Hop 7 Fill 2.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Electronic\\160 DnB Beat.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Country\\103 Country Waltz Ride Fill 5.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\eval_session\\3_soul-groove3_86_beat_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\World\\125 W African 1 Fill 4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session1\\37_hiphop_100_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\31_latin-samba_116_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer3\\session2\\27_jazz_92_beat_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Country\\130 Country 2-Feel Fill 3.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\129_afrocuban-bembe_122_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer3\\session1\\24_rock_120_beat_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\World\\120 High Life 2 Fill 1.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\World\\190 Cumbia Fill 2.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session3\\121_rock_93_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\137_funk-fast_125_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\115 BPM POPCORN FUNK\\Ride 007 (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\World\\100 Bembe.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\8_jazz-march_176_beat_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Rock\\140 Driving Rock 3.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session2\\83_country_78_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\eval_session\\4_soul-groove4_80_beat_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\263_funk-purdieshuffle_130_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\138 BPM FUSION FUNK\\Ending 002 (5).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Jazz\\186 Jazz Bossa Fill 5.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\115 BPM POPCORN FUNK\\Ride 004 Break (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session3\\17_pop-soft_83_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Electronic\\150 Jungle Displaced Fill 3.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Hip Hop\\100 Hip Hop Classic.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Funk\\110 Cold Fill 2.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Pop\\100 Pop 16th Feel 2 Fill 1.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Metal\\174 Old School OH.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Funk\\090 16th Funk 2 Fill 4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Rock\\120 Rock Basic 3 Crash.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\129_afrocuban-bembe_122_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Hip Hop\\085 Hip Hop 1 Fill 2.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\111_funk_95_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\R&B\\135 Shuffle Ghosts 2 Crash.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session2\\55_soul-motown_148_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Hip Hop\\092 Hip Hop 3 Fill 2.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\26_country_114_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\R&B\\085 Modern Fill 1.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\095 BPM FUNKY MAGNUS\\Ride 005 Bell (4).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\115 BPM POPCORN FUNK\\Hihat 004 (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Funk\\102 Funk 8th Feel 2 Ride.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session3\\116_rock_95_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Hip Hop\\088 Hip Hop 7 Fill 3.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\228_rock-halftime_140_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Pop\\075 6-8 Pop Stick Crash.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Electronic\\125 Disco Beat Fill 3.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Rock\\100 16th Rock Fill 3.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\88_punk_144_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session3\\152_soul_98_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Country\\130 Country 2-Feel Fill 2.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Hip Hop\\089 West Coast 10 Fill 2.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\086 BPM MODERN SHUFFLE FUNK\\Hihat 010 (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session3\\7_rock_60_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\eval_session\\6_hiphop-groove6_87_beat_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\R&B\\150 Motown Beat Fill 2.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session3\\101_hiphop_70_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session3\\57_funk_112_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\253_funk-purdieshuffle_130_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\26_jazz-funk_116_fill_4-4.mid']

In [29]:
중요해~

['C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer7\\session1\\40_hiphop_100_beat_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\240_funk-purdieshuffle_130_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\50_punk_128_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session2\\119_afrocuban-bembe_122_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\111 BPM TOP FUNK\\Verse 003 (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\gmd\\drummer1\\session1\\195_reggae_78_fill_4-4.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\Pop\\075 6-8 Pop Stick Fill 5.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variety Pack\\Variety Pack GM\\R&B\\113 Boogaloo Fill 1.mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\OddGrooves_Funky_Drumming\\ODDGROVES_FUNKY_DRUMMING-gm\\115 BPM POPCORN FUNK\\Hihat 001 (8).mid',
 'C:\\Users\\KIST\\Desktop\\MIDI\\Groove Monkee Variet

In [18]:
import shutil
import os

cnt = 0

for i in files:
    shutil.copyfile(i, './test_midi/'+str(cnt)+'.mid')
    cnt+=1

In [20]:
for i in files:
    try:
        os.remove(i)
    except:
        pass

In [53]:
monkee_midi_list = glob(r"C:\Users\KIST\Desktop\MIDI\Groove*\**\**\*.mid")

In [54]:
asd = []
for i in monkee_midi_list:
    if i[-10:-6] == 'Fill':
        asd.append(i[:-11])

In [55]:
asd = list(set(asd))

In [57]:
cnt = 1

for i in asd:
    fill = []
    beat = []
    for j in monkee_midi_list:
        if i in j:
            if 'fill' in j.lower():
                fill.append(j)
            else:
                beat.append(j)
    
    for b in beat:
        for f in fill:
            b_midi = MidiFile(b, clip=True)
            f_midi = MidiFile(f, clip=True)
            b_on_sec = 0
            f_on_sec = 0
            b_event = []
            f_event = []

            for msg in b_midi.tracks[b_midi.tracks.__len__() - 1]:
                note = str(msg).split()
                if len(note) == 5:
                    b_on_sec += msg.dict()['time']

                    if note[0] == 'note_on' and note[3] != 'velocity=0':
                        if [round(b_on_sec/60), msg.dict()['note']] not in b_event:
                            b_event.append([round(b_on_sec/60), msg.dict()['note']])
            
            for msg in f_midi.tracks[f_midi.tracks.__len__() - 1]:
                note = str(msg).split()
                if len(note) == 5:
                    f_on_sec += msg.dict()['time']

                    if note[0] == 'note_on' and note[3] != 'velocity=0':
                        if [round(f_on_sec/60), msg.dict()['note']] not in f_event:
                            f_event.append([round(f_on_sec/60), msg.dict()['note']])
                
            if b_event[-1][0]%16 != 0:
                add = 1
            else:
                add = 0
            b_beat = pd.DataFrame(0, columns = np.arange(10), index = np.arange((b_event[-1][0]//16 + add) * 16))
            f_beat = pd.DataFrame(0, columns = np.arange(10), index = np.arange((f_event[-1][0] + 1)))

            for e in b_event:
                b_beat.loc[e[0], classify(e[1], midi=b)] = 1
            if (b_beat[-15:] == np.zeros((15,10))).all().all():
                b_beat = b_beat[:-16]

            for e in f_event:
                f_beat.loc[e[0], classify(e[1], midi=f)] = 1

            bf = pd.concat([b_beat, f_beat])

            print(b)
            print(f)
            bf.to_csv('./midi2df_0216/fill/' + str(cnt) + '.csv', index = False, header=False)
            cnt += 1



            




C:\Users\KIST\Desktop\MIDI\Groove Monkee Variety Pack\Variety Pack GM\Metal\200 2x Kick Downbeat OH Crash.mid
C:\Users\KIST\Desktop\MIDI\Groove Monkee Variety Pack\Variety Pack GM\Metal\200 2x Kick Downbeat OH Fill 1.mid
C:\Users\KIST\Desktop\MIDI\Groove Monkee Variety Pack\Variety Pack GM\Metal\200 2x Kick Downbeat OH Crash.mid
C:\Users\KIST\Desktop\MIDI\Groove Monkee Variety Pack\Variety Pack GM\Metal\200 2x Kick Downbeat OH Fill 2.mid
C:\Users\KIST\Desktop\MIDI\Groove Monkee Variety Pack\Variety Pack GM\Metal\200 2x Kick Downbeat OH Crash.mid
C:\Users\KIST\Desktop\MIDI\Groove Monkee Variety Pack\Variety Pack GM\Metal\200 2x Kick Downbeat OH Fill 3.mid
C:\Users\KIST\Desktop\MIDI\Groove Monkee Variety Pack\Variety Pack GM\Metal\200 2x Kick Downbeat OH Crash.mid
C:\Users\KIST\Desktop\MIDI\Groove Monkee Variety Pack\Variety Pack GM\Metal\200 2x Kick Downbeat OH Fill 4.mid
C:\Users\KIST\Desktop\MIDI\Groove Monkee Variety Pack\Variety Pack GM\Metal\200 2x Kick Downbeat OH Crash.mid
C:\Use

In [36]:
a = pd.read_csv('./3.csv.gzip', compression='gzip')

with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(a)

    0  1  2  3  4  5  6  7  8  9
0   0  0  0  0  0  0  0  0  0  0
1   0  0  0  0  0  0  0  0  0  0
2   0  0  0  0  0  0  0  0  0  0
3   0  0  0  0  0  0  0  0  0  0
4   0  0  0  0  0  0  0  0  0  0
5   0  0  0  0  0  0  0  0  0  0
6   0  0  0  0  0  0  0  0  0  0
7   0  0  0  0  0  0  0  0  0  0
8   0  0  0  0  0  0  0  0  0  0
9   0  0  0  0  0  0  0  0  0  0
10  0  0  0  0  0  0  0  0  0  0
11  0  0  0  0  0  0  0  0  0  0
12  0  0  0  0  0  0  0  0  0  0
13  0  0  0  0  0  0  0  0  0  0
14  0  0  0  0  0  0  0  0  0  0
15  0  0  0  0  0  0  0  0  0  0
16  1  0  0  0  0  0  1  0  0  0
17  0  0  0  0  0  0  0  0  0  0
18  0  0  0  0  0  0  0  0  0  0
19  0  0  0  0  0  0  0  0  0  0
20  1  0  0  0  0  0  1  0  0  0
21  0  0  0  0  0  0  0  0  0  0
22  0  0  0  0  0  0  0  0  0  0
23  0  0  0  0  0  0  0  0  0  0
24  1  0  0  0  0  0  1  0  0  0
25  0  0  0  0  0  0  0  0  0  0
26  0  0  0  0  0  0  0  0  0  0
27  0  0  0  0  0  0  0  0  0  0
28  1  0  0  0  0  0  1  0  0  0
29  0  0  

In [ ]:
a = pd.read_csv('./bar_dataset2/merged_beat/44.csv.gzip', compression='gzip')

with pd.option_context('display.max_rows', None, 'display.max_columns', None):  # more options can be specified also
    print(a)

In [30]:
beat_gzip = glob('./midi2df_0109/beat/*.csv.gzip')

In [47]:
seven_kind_arr = [
   # bd sn mt lt oh ch ri 
    [1, 0, 0, 0, 0, 0, 0], #0
    [0, 1, 0, 0, 0, 0, 0], #1
    [0, 0, 1, 0, 0, 0, 0], #2
    [0, 0, 0, 1, 0, 0, 0], #3
    [0, 0, 0, 0, 1, 0, 0], #4
    [0, 0, 0, 0, 0, 1, 0], #5
    [0, 0, 0, 0, 0, 0, 1], #6
    [1, 0, 0, 0, 0, 1, 0], #7
    [1, 0, 0, 0, 1, 0, 0], #8
    [1, 0, 0, 0, 0, 0, 1], #9
    [1, 0, 0, 1, 0, 0, 0], #10
    [1, 1, 0, 0, 0, 0, 0], #11
    [0, 1, 0, 0, 0, 1, 0], #12
    [0, 1, 0, 0, 1, 0, 0], #13
    [0, 1, 0, 0, 0, 0, 1], #14
    [0, 1, 0, 1, 0, 0, 0], #15
    [0, 1, 0, 0, 0, 0, 1], #16
    [0, 0, 1, 1, 0, 0, 0], #17
    [1, 1, 0, 0, 0, 1, 0], #18
    [1, 1, 0, 0, 1, 0, 0], #19
    [1, 1, 0, 0, 0, 0, 1], #20
    [0, 0, 0, 0, 0, 0, 0]
]


# bd sn ht mt lt oh ch cr ri
checking_arr = [
    [0, 0, 0, 0, 0, 0, 0, 0, 0], # 0 null
    [1, 0, 0, 0, 0, 0, 0, 0, 0], # 1  B
    [1, 0, 0, 0, 0, 0, 0, 1, 0], # 2  B+C
    [1, 0, 0, 0, 0, 0, 1, 0, 0], # 3  B+CH
    [1, 0, 0, 0, 1, 0, 0, 0, 0], # 5  B+FT
    [1, 0, 1, 0, 0, 0, 0, 0, 0], # 4  B+HT
    [1, 0, 0, 1, 0, 0, 0, 0, 0], # 6  B+MT
    [1, 0, 0, 0, 0, 1, 0, 0, 0], # 7  B+OH
    [1, 0, 0, 0, 0, 0, 0, 0, 1], # 8  B+R
    [0, 0, 0, 0, 0, 0, 1, 0, 0], # 9  CH
    [0, 0, 0, 0, 1, 0, 1, 0, 0], # 11 CH+FT
    [0, 0, 1, 0, 0, 0, 1, 0, 0], # 10 CH+HT
    [0, 0, 0, 0, 0, 0, 1, 0, 1], # 12 CH+R
    [0, 0, 0, 0, 1, 0, 0, 0, 0], # 15 FT
    [0, 0, 1, 0, 0, 0, 0, 0, 0], # 13 HT
    [0, 0, 1, 0, 1, 0, 0, 0, 0], # 14 HT+FT
    [0, 0, 0, 1, 0, 0, 0, 0, 0], # 16 MT
    [0, 0, 0, 0, 0, 1, 0, 0, 0], # 17 OH
    [0, 0, 0, 0, 0, 0, 0, 0, 1], # 18 R
    [0, 1, 0, 0, 0, 0, 0, 0, 0], # 19 S
    [1, 1, 0, 0, 0, 0, 0, 0, 0], # 20 S+B
    [1, 1, 0, 0, 0, 0, 1, 0, 0], # 21 S+B+CH
    [1, 1, 0, 0, 1, 0, 0, 0, 0], # 22 S+B+FT
    [1, 1, 0, 0, 0, 1, 0, 0, 0], # 23 S+B+OH
    [1, 1, 0, 0, 0, 0, 0, 0, 1], # 24 S+B+R
    [0, 1, 0, 0, 0, 0, 0, 1, 0], # 25 S+C
    [0, 1, 0, 0, 0, 0, 1, 0, 0], # 26 S+CH
    [0, 1, 0, 0, 1, 0, 0, 0, 0], # 27 S+FT
    [0, 1, 0, 0, 0, 1, 0, 0, 0], # 28 S+OH
    [0, 1, 0, 0, 0, 0, 0, 0, 1], # 29 S+R
    # [0, 0, 0, 0, 0, 0, 0, 1, 0], # 30 C
]


In [63]:
cnt = 1
unit = 32

for i in range(1,1263):
    # lst = []
    
    asd = pd.read_csv('./midi2df_0216/fill/' + str(i) + '.csv', header=None)
    # asd = asd.drop('9', axis=1)
    
    # for ii in np.array(asd):
    #     if list(ii) in checking_arr:
    #         lst.append(checking_arr.index(list(ii)))
    #     else:
    #         lst.append('err')
    
    # print(i)
    # print(set(lst))
    # print('---')
    print(asd)
    
    if asd.shape[0] >= unit:
        for _ in range(asd.shape[0]//32 + 1):
            useful = True
            while_loop_cnt = 0
            while True:
                rng = random.randint(0, asd.shape[0]-unit)
                imsi = asd[rng:rng+unit]
                while_loop_cnt += 1
                # print(imsi.iloc[-1:].values.tolist()[0][:-1])
                if imsi.iloc[-1:].values.tolist()[0][:-1] != [0,0,0,0,0,0,0,0,0]:
                # if imsi.iloc[-1:9].values.tolist() != [0,0,0,0,0,0,0,0,0]:
                    break
                elif while_loop_cnt > 1000:
                    useful=False
                    break
            # print(imsi)
            asdd = imsi.drop(9, axis=1)
            # asdd = imsi
            for i in np.array(asdd):
                if list(i) not in checking_arr:
                    useful = False
            if useful:
                asdd.to_csv('./new_2bar_0216/fill_' + str(cnt) + '.csv', index=False, header=False)
                cnt += 1
            
            # asdd.to_csv('./new_2bar_non_filter/' + str(cnt) + '.csv.gzip', compression='gzip', index=False)
            # cnt += 1
            

    0  1  2  3  4  5  6  7  8  9
0   1  1  0  0  0  0  0  1  0  0
1   1  0  0  0  0  0  0  0  0  0
2   1  0  0  0  0  0  0  0  0  0
3   1  0  0  0  0  0  0  0  0  0
4   1  1  0  0  0  1  0  0  0  0
.. .. .. .. .. .. .. .. .. .. ..
75  1  0  0  1  0  0  0  0  0  0
76  1  0  0  0  1  0  0  0  0  0
77  1  0  0  0  1  0  0  0  0  0
78  1  0  0  0  1  0  0  0  0  0
79  1  0  0  0  1  0  0  0  0  0

[80 rows x 10 columns]
    0  1  2  3  4  5  6  7  8  9
0   1  1  0  0  0  0  0  1  0  0
1   1  0  0  0  0  0  0  0  0  0
2   1  0  0  0  0  0  0  0  0  0
3   1  0  0  0  0  0  0  0  0  0
4   1  1  0  0  0  1  0  0  0  0
.. .. .. .. .. .. .. .. .. .. ..
75  1  0  0  1  0  0  0  0  0  0
76  1  0  1  0  0  0  0  0  0  0
77  1  0  1  0  0  0  0  0  0  0
78  1  0  1  0  0  0  0  0  0  0
79  1  0  1  0  0  0  0  0  0  0

[80 rows x 10 columns]
    0  1  2  3  4  5  6  7  8  9
0   1  1  0  0  0  0  0  1  0  0
1   1  0  0  0  0  0  0  0  0  0
2   1  0  0  0  0  0  0  0  0  0
3   1  0  0  0  0  0  0  0  

In [38]:
unit = 32

cnt = 1
for i in range(1,1263):
    asd = pd.read_csv('./midi2df/fill/' + str(i) + '.csv.gzip', compression='gzip')
    
    if asd.shape[0] >= unit:
        for _ in range(asd.shape[0]//32 + 1):
            useful = True
            while_loop_cnt = 0
            while True:
                rng = random.randint(0, asd.shape[0]-unit)
                imsi = asd[rng:rng+unit]
                while_loop_cnt += 1
                if imsi.iloc[-1:].values.tolist() != [0,0,0,0,0,0,0,0,0,0]:
                    break
                elif while_loop_cnt > 1000:
                    useful=False
                    break
            asdd = imsi.drop('9', axis=1)
            # asdd = imsi
            for i in np.array(asdd):
                if list(i) not in checking_arr:
                    useful = False
            if useful:
                # asdd.to_csv('./new_2bar_0119_/fill__' + str(cnt) + '.csv.gzip', compression='gzip', index=False)
                cnt += 1
            
            # asdd.to_csv('./new_2bar_non_filter/' + str(cnt) + '.csv.gzip', compression='gzip', index=False)
            # cnt += 1

In [45]:
asdd.iloc[-1:].values.tolist()

[[0, 0, 0, 0, 0, 0, 0, 0, 0]]

In [21]:
imsi

0  1  2  3  4  5  6  7  8  9
9   0  1  0  0  0  0  1  0  0  0
10  0  1  0  0  0  1  0  0  0  0
11  0  0  0  0  0  0  0  0  0  0
12  1  1  0  0  0  0  1  0  0  0
13  0  0  0  0  0  0  1  0  0  0
14  0  0  0  0  0  1  0  0  0  0
15  0  0  0  0  0  0  0  0  0  0
16  1  0  0  0  0  0  1  0  0  0
17  0  0  0  0  0  0  1  0  0  0
18  0  0  0  0  0  1  0  0  0  0
19  0  0  0  0  0  0  0  0  0  0
20  1  1  0  0  0  0  1  0  0  0
21  0  0  0  0  0  0  1  0  0  0
22  0  0  0  0  0  1  0  0  0  0
23  0  1  0  0  0  0  0  0  0  0
24  1  0  0  0  0  0  1  0  0  0
25  0  1  0  0  0  0  1  0  0  0
26  0  1  0  0  0  1  0  0  0  0
27  0  0  0  0  0  0  0  0  0  0
28  1  1  0  0  0  0  1  0  0  0
29  0  0  0  0  0  0  1  0  0  0
30  0  0  0  0  0  1  0  0  0  0
31  0  0  0  0  0  0  0  0  0  0
32  1  0  0  0  0  0  1  0  0  0
33  0  0  0  0  0  0  1  0  0  0
34  0  0  0  0  0  1  0  0  0  0
35  0  0  0  0  0  0  0  0  0  0
36  1  1  0  0  0  0  1  0  0  0
37  0  0  0  0  0  0  1  0  0  0
38  0  0  0  0  0  1  0  0  0  0
39  0  1  0  0  0  0  0  0  0  0
40  1  0  0  0  0  0  1  0  0  0

In [23]:
imsi.iloc[31][0]

1

In [18]:
asdd

0  1  2  3  4  5  6  8  9
9   0  1  0  0  0  0  1  0  0
10  0  1  0  0  0  1  0  0  0
11  0  0  0  0  0  0  0  0  0
12  1  1  0  0  0  0  1  0  0
13  0  0  0  0  0  0  1  0  0
14  0  0  0  0  0  1  0  0  0
15  0  0  0  0  0  0  0  0  0
16  1  0  0  0  0  0  1  0  0
17  0  0  0  0  0  0  1  0  0
18  0  0  0  0  0  1  0  0  0
19  0  0  0  0  0  0  0  0  0
20  1  1  0  0  0  0  1  0  0
21  0  0  0  0  0  0  1  0  0
22  0  0  0  0  0  1  0  0  0
23  0  1  0  0  0  0  0  0  0
24  1  0  0  0  0  0  1  0  0
25  0  1  0  0  0  0  1  0  0
26  0  1  0  0  0  1  0  0  0
27  0  0  0  0  0  0  0  0  0
28  1  1  0  0  0  0  1  0  0
29  0  0  0  0  0  0  1  0  0
30  0  0  0  0  0  1  0  0  0
31  0  0  0  0  0  0  0  0  0
32  1  0  0  0  0  0  1  0  0
33  0  0  0  0  0  0  1  0  0
34  0  0  0  0  0  1  0  0  0
35  0  0  0  0  0  0  0  0  0
36  1  1  0  0  0  0  1  0  0
37  0  0  0  0  0  0  1  0  0
38  0  0  0  0  0  1  0  0  0
39  0  1  0  0  0  0  0  0  0
40  1  0  0  0  0  0  1  0  0

In [48]:
pd.read_csv('./new_2bar_0213/fill_34.csv.gzip',compression='gzip').to_numpy()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0,

In [9]:
checking_arr.index([0,0,0,0,0,0,0,0,0])

0

In [55]:
cnt = 1

for midi in os.listdir('./new_2bar_0213/'):
    csv = pd.read_csv('./new_2bar_0213/' + midi, compression='gzip').to_numpy()
    seq = []
    for note in csv:
        seq.append(checking_arr.index(note.tolist()))
    
    seq = [int(s) for s in seq]
    a = pd.DataFrame(np.zeros((32,29)))
    
    # tmp = 0
    # print(seq)
    # print('----')
    
    for i in range(32):
        if seq[i] != 0:
            a.iloc[i,seq[i]-1] = 1

        # if tmp == 30:
        #     a.to_csv('./bar2singlelabel_masked/' + midi, index=False, compression='gzip')
        # tmp += 1
    # print(a)
    a.to_csv('./bar2singlelabel_0213/'+str(cnt).zfill(4)+'.csv.gzip', index=False, compression='gzip')
    cnt += 1
    

In [63]:
a = pd.DataFrame(np.zeros((5,3)))

In [72]:
seq = [1.0 , 2.0]

TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

In [66]:
a.iloc[2,0] = 1

In [70]:
a.iloc[3,2] = 1

In [71]:
a

0    1    2
0  0.0  0.0  0.0
1  0.0  0.0  0.0
2  1.0  0.0  0.0
3  0.0  0.0  1.0
4  0.0  0.0  0.0

In [26]:
ass

0  1  2  3  4  5  6  8  9
0   1  0  0  0  0  0  1  0  0
1   1  0  0  0  0  0  1  0  0
2   0  0  0  0  0  0  0  0  0
3   0  1  0  0  0  0  1  0  0
4   0  0  0  0  0  0  1  0  0
5   0  0  0  0  0  0  1  0  0
6   0  0  0  0  0  0  0  0  0
7   1  0  0  0  0  0  1  0  0
8   0  0  0  0  0  0  1  0  0
9   1  0  0  0  0  0  1  0  0
10  0  0  0  0  0  0  0  0  0
11  0  1  0  0  0  0  1  0  0
12  0  0  0  0  0  0  1  0  0
13  0  0  0  0  0  0  1  0  0
14  0  1  0  0  0  0  0  0  0
15  0  0  0  0  0  0  1  0  0
16  1  0  0  0  0  0  1  0  0
17  1  0  0  0  0  0  1  0  0
18  0  0  0  0  0  0  0  0  0
19  0  1  0  0  0  0  1  0  0
20  0  0  0  0  0  0  1  0  0
21  0  0  0  0  0  1  0  0  0
22  0  0  0  0  0  0  0  0  0
23  1  0  0  0  0  0  1  0  0
24  0  0  0  0  0  0  1  0  0
25  1  0  0  0  0  0  1  0  0
26  0  0  0  0  0  0  0  0  0
27  0  1  0  0  0  0  1  0  0
28  0  0  0  0  0  0  1  0  0
29  1  0  0  0  0  0  1  0  0
30  0  1  0  0  0  0  0  0  0
31  0  0  0  0  0  0  1  0  0

In [246]:
for i in np.array(asdd):
    if list(i) not in seven_kind_arr:
        print(i)

[1 0 0 0 0 1 1]
[0 0 0 0 0 1 1]
[0 0 1 0 0 0 1]
[0 0 0 0 0 1 1]
[0 1 0 0 0 1 1]
[1 0 1 0 0 1 1]
[0 0 0 1 0 0 1]
[0 0 0 0 0 1 1]
[0 0 1 0 0 1 0]
[0 1 0 0 0 1 1]
[1 0 1 0 0 1 1]
[0 0 0 0 0 1 1]
[0 0 0 0 0 1 1]
[0 0 1 0 0 1 1]
[1 0 0 0 0 1 1]
[0 0 1 0 0 1 0]
[0 1 0 0 0 1 1]
[1 0 1 0 0 1 1]
[0 0 0 0 0 1 1]
[0 0 0 0 0 1 1]
[1 0 1 0 0 1 1]
[1 0 0 0 0 1 1]
[1 0 0 0 0 1 1]
[0 1 0 0 0 1 1]
[1 0 1 0 0 1 1]
[0 0 0 0 0 1 1]
[0 0 0 0 0 1 1]
[0 0 1 0 0 1 1]
[0 0 0 0 0 1 1]
[0 0 0 0 0 1 1]
[1 0 0 0 0 1 1]
[1 0 1 0 0 1 1]
[0 0 0 0 0 1 1]
[0 0 0 0 0 1 1]
[0 0 1 0 0 0 1]
[0 0 0 0 0 1 1]
[0 1 0 0 0 1 1]
[1 0 0 0 0 1 1]
[1 0 0 0 0 1 1]
[0 0 0 0 0 1 1]
[0 0 0 0 0 1 1]
[0 0 1 0 0 0 1]
[0 0 0 0 0 1 1]
[0 0 1 0 0 1 0]
[0 1 0 0 0 1 1]
[1 0 0 0 0 1 1]
[1 0 1 0 0 1 1]
[0 0 0 0 0 1 1]
[0 0 0 0 0 1 1]
[0 0 1 0 0 1 0]
[0 0 1 0 0 1 0]
[0 0 1 0 0 1 0]
[0 0 1 0 0 1 0]
[0 0 1 0 0 1 0]
[0 0 1 0 0 1 0]
[0 0 1 0 0 1 0]


In [226]:
for i in range(1,10):
    print(i)

1
2
3
4
5
6
7
8
9
