In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd

from tensorflow.keras.layers import Dense, LSTM, Input, TimeDistributed
from tensorflow.keras.models import Model

In [2]:
train=[]
train_y=[]

for i in range(1,5001):
    train.append(pd.read_csv('./masked_dataset/beat/'+str(i)+'.csv.gzip', compression='gzip').to_numpy())
    train_y.append(pd.read_csv('./dataset/beat/'+str(i)+'.csv.gzip', compression='gzip').to_numpy())
    

In [3]:
train = np.array(train)
train_y = np.array(train_y)

In [19]:
train = train.swapaxes(1,2)
train_y = train_y.swapaxes(1,2)

In [4]:
model = tf.keras.models.Sequential()

In [5]:
# model.add(Input(shape=(9,32)))

# inputs = Input(shape=(9,32))
# lstm =  tf.keras.layers.Bidirectional(LSTM(units=32, return_sequences=True, activation='sigmoid'))(inputs)
# outputs = tf.keras.layers.Bidirectional(LSTM(units=32, return_sequences=False, activation='sigmoid'))(lstm)
# forward = LSTM(units=16, return_sequences=True, activation='sigmoid')
# backward = LSTM(units=16, return_sequences=True, activation='sigmoid', go_backwards=True)

# model.add(tf.keras.layers.Bidirectional(forward, backward_layer=backward, input_shape=(9,32)))
# model.add(LSTM(units=32, return_sequences=True, activation='sigmoid', input_shape=(9,32)))
model.add(LSTM(units=9, return_sequences=True, activation='sigmoid', input_shape=(32,9)))
# model = Model(inputs, outputs)

In [6]:
# model.compile(loss = tf.keras.losses.binary_crossentropy, optimizer='rmsprop')
model.compile(loss = tf.keras.losses.mse, optimizer='adam')

In [ ]:
model.fit(train.astype('float32'),train_y.astype('float32'), epochs=40)

In [5]:
trainn=[]
testn=[]

for i in range(10000,10100):
    trainn.append(pd.read_csv('./masked_dataset/beat/'+str(i)+'.csv.gzip', compression='gzip').to_numpy())
    testn.append(pd.read_csv('./dataset/beat/'+str(i)+'.csv.gzip', compression='gzip').to_numpy())
    

In [6]:
trainn = np.array(trainn)
testn = np.array(testn) 

In [11]:
train.shape

(5000, 32, 9)

In [20]:
dec = np.zeros_like(train)

dec.shape

(5000, 32, 9)

In [21]:
for i in range(dec.shape[0]):
    for j in range(dec.shape[1]):
        if j != 0:
            dec[i][j] = train_y[i][j-1]

In [22]:
trainn = trainn.swapaxes(1,2)
testn = testn.swapaxes(1,2)

In [23]:
decn = np.zeros_like(testn)
for i in range(decn.shape[0]):
    for j in range(decn.shape[1]):
        if j != 0:
            decn[i][j] = testn[i][j-1]

In [24]:
testn

array([[[0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 1, 0, ..., 1, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0]],

       [[1, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 0, 0],
        ...,
        [0, 1, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 1, 0, 0],
        [0, 1, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [1, 1, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 0, 0]],

       ...,

       [[0, 1, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 1, 0, ..., 1, 0, 1],
        ...,
        [0, 1, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 1, 0, 1],
        [1, 1, 0, ..., 0, 0, 0]],

       [[1, 1, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 1, 0, 0],
        ...,
        [0, 1, 0, ..., 

In [25]:
decn

array([[[0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 0, 0],
        ...,
        [0, 1, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 1, 0, 0],
        [0, 1, 0, ..., 0, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [1, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 1, 0, 0]],

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [1, 1, 0, ..., 0, 0, 0],
        ...,
        [0, 1, 0, ..., 0, 0, 0],
        [1, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]],

       ...,

       [[0, 0, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 0, 0, 1],
        ...,
        [1, 0, 0, ..., 0, 0, 1],
        [0, 1, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 1, 0, 1]],

       [[0, 0, 0, ..., 0, 0, 0],
        [1, 1, 0, ..., 0, 0, 0],
        [0, 1, 0, ..., 0, 0, 0],
        ...,
        [1, 1, 0, ..., 

In [ ]:
asdf = model.predict(trainn)

asdf = asdf.round()

In [ ]:
model.evaluate(trainn, testn)

In [ ]:
i = 10
print(trainn[i])
print('-'*10)
print(asdf[i].astype(int))
print('-'*10)
print(testn[i])

--

In [52]:
encoder_inputs = Input(shape=(32,9))
encoder_lstm = LSTM(units=512, return_state=True, dropout=0.1, unroll=True, recurrent_dropout=0.1)

encoder_outputs, state_h, state_c = encoder_lstm(encoder_inputs)

encoder_states = [state_h, state_c]

In [53]:
decoder_inputs = Input(shape=(None,9))
decoder_lstm = LSTM(units=512, return_sequences=True, return_state=True, dropout=0.1, recurrent_dropout=0.1)

decoder_outputs, _, _ = decoder_lstm(decoder_inputs, initial_state = encoder_states)

decoder_dense = Dense(9, activation='sigmoid')

decoder_outputs = decoder_dense(decoder_outputs)


In [54]:
# if model is not None:
del model
model = Model([encoder_inputs, decoder_inputs], decoder_outputs)

callback = tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=10)

In [55]:
model.compile(optimizer=tf.keras.optimizers.Adam(), loss=tf.keras.losses.binary_crossentropy)

In [56]:
with tf.device('/gpu:0'):
    model.fit(x=[train, dec], y=train_y, epochs=5000, callbacks=callback, validation_split=0.2)

Epoch 1/5000
125/125 [==============================] - 28s 194ms/step - loss: 0.3213 - val_loss: 0.2909
Epoch 2/5000
125/125 [==============================] - 23s 186ms/step - loss: 0.2698 - val_loss: 0.2636
Epoch 3/5000
125/125 [==============================] - 24s 189ms/step - loss: 0.2464 - val_loss: 0.2508
Epoch 4/5000
125/125 [==============================] - 24s 189ms/step - loss: 0.2350 - val_loss: 0.2431
Epoch 5/5000
125/125 [==============================] - 23s 183ms/step - loss: 0.2266 - val_loss: 0.2369
Epoch 6/5000
125/125 [==============================] - 23s 183ms/step - loss: 0.2186 - val_loss: 0.2252
Epoch 7/5000
125/125 [==============================] - 23s 186ms/step - loss: 0.2107 - val_loss: 0.2229
Epoch 8/5000
125/125 [==============================] - 23s 187ms/step - loss: 0.2018 - val_loss: 0.2123
Epoch 9/5000
125/125 [==============================] - 23s 187ms/step - loss: 0.1939 - val_loss: 0.2086
Epoch 10/5000
125/125 [==============================] 

In [57]:
model.evaluate(x=[trainn, decn], y=testn)

4/4 [==============================] - 0s 64ms/step - loss: 0.2425


0.24249206483364105

In [58]:
asd = model.predict(x=[trainn, decn])
asd = asd.round()

In [60]:
i = 10
print(trainn[i])
print('-'*10)
print(asd[i].astype(int))
print('-'*10)
print(testn[i])

[[0 1 0 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 1 0 0]
 [0 1 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [1 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0]
 [1 0 1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 1 0 0]
 [0 1 0 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 1 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 1 0 0]]
----------
[[0 1 0 0 0 0 0 0 0]
 [1 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 1 0 0]
 [0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [0 1 0 0 1 0 1 0 0]
 [0 1 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0]
 [1 0 0 0 1 0 1 0 0]
 [0 1 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0]
 